### PR TITLE
fix:  cargo-doc warning & update docs for deprecated method

### PR DESCRIPTION
**Pull request by muse254**
- Fixing cargo doc warning. 
> warning: unresolved link to `WasmtimeEngineProviderBuilder`
- The method `WasmtimeEngineProvider` is deprecated, updating developer docs
https://github.com/wapc/wapc-rs/blob/67a88e84b6f214872bcd2b119b34cf7cfb3f78cd/crates/wasmtime-provider/src/lib.rs#L278-L289

### CODE REVIEW

**Comment by pkedy** [comment]
@flavio Could you please review so that updated README shows up in crates.io when I release?

**Review by flavio — APPROVED** [review]
Thanks for the fixes!

**Comment by flavio** [comment]
@pkedy merged, you can go ahead with the release

**Comment by pkedy** [comment]
https://crates.io/crates/wasmtime-provider/1.15.0

**Pull request merged**
