### PR TITLE
automation: automatic updates or Rust version

### PR DESCRIPTION
**Pull request by flavio**
Use updatecli to automatically detect updates of Rust to be done inside of `rust-toolchain.toml`.

Neither dependabot nor renovatebot can handle that.

### CODE REVIEW

**Comment by flavio** [comment]
@olblak: could you please double check this PR to make sure everything is fine/idiomatic? We might want to use this automation also inside of Kubewarden

@pkedy, @jsoverson: @olblak is the maintainer of [updatecli](https://www.updatecli.io/) and a colleague of mine.

**Comment by olblak** [comment]
I see several improvements, let me open a pull-request on your fork

**Comment by olblak** [comment]
@flavio I opened https://github.com/flavio/wapc-rs/pull/1

**Comment by olblak** [comment]
@flavio Btw in case you need to reuse this update policy on many different repositories, since December 24, you can also use Updatecli policies from a registry.

It's a little bit more effort upfront as you need to publish the manifest (and metadata) to an OCI registry like dockerhub or ghcr.io but then you can reuse them using a updatecli-compose.yaml file like this one [github.com/updatecli/updatecli](https://github.com/updatecli/updatecli/blob/main/update-compose.yaml)

**Review by olblak — APPROVED** [review]

**Review by pkedy — APPROVED** [review]

**Pull request merged**
