### PR TITLE
expose `wasmtime_provider::WasmtimeEngineProviderPre`

### PR DESCRIPTION
**Pull request by flavio**
Make the `wasmtime_provider::WasmtimeEngineProviderPre` public. This allows end users to implement optimizations inside of their code base.

On top of that, update to latest Rust release and fix some small linter warnings caused by that.

Once this PR is merged it would be great to release a new **minor** version of the `wasmtime_provider` crate (a minor release since the API is changed by the introduction of this new public struct).

### CODE REVIEW

**Comment by flavio** [comment]
@pkedy , @jsoverson : could you please take a look at this PR and, if merged, tag a new release of the wasmtime provider? :pray:

**Review by pkedy — APPROVED** [review]
LGTM

**Comment by pkedy** [comment]
Happy new year, @flavio !

https://crates.io/crates/wasmtime-provider/1.12.1

**Comment by flavio** [comment]
@pkedy thanks for the release and happy new year!

**Pull request merged**
